steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/sit737-23t1-silman-ara-7d36463/zagapp'
      - '.'

  # Run unit tests
  - name: 'gcr.io/sit737-23t1-silman-ara-7d36463/zagapp'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install mocha && npm test & npm stop'
