steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/sit737-23t1-silman-ara-7d36463/zagapp'
      - '.'

  # Run unit tests
  - name: 'gcr.io/sit737-23t1-silman-ara-7d36463/zagapp'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install mocha && npm test'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/sit737-23t1-silman-ara-7d36463/zagapp'

  # Authentication
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'hello-cluster'
      - '--region'
      - 'australia-southeast2-a'

  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=australia-southeast2-a'
      - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast2-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'

  # Deploye the kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'create'
      - 'deployment'
      - 'hello-server'
      - '--image=gcr.io/sit737-23t1-silman-ara-7d36463/zagapp'