apiVersion: apps/v1
kind: Deployment
metadata:
  name: zagdeployment
  labels:
    app: zagapp
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: zagnode
        image: gcr.io/sit737-23t1-silman-ara-7d36463/zagapp
        ports:
        - containerPort: 8080